"""creación de tablas DEMRE inicial

Revision ID: 8d16e09a1b3f
Revises: 41972245f9b9
Create Date: 2025-11-02 15:38:22.900710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d16e09a1b3f'
down_revision: Union[str, Sequence[str], None] = '41972245f9b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
